# Config from own experience and https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Run Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14 using Cache
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      # Validation does not work for some reason. Gradle Wrapper was created by using gradle v7.2 installed from the apt repository.
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.0.1
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

